#!/usr/bin/env bash
# This script tells the story of the passwd file

while IFS=':' read -r username _ uid gid info homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
