#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but on the 9th time, it displays different things

count=1
while [ "$count" -le 10 ]; do
  if [ "$count" -eq 9 ]; then
     echo "Best School"
     echo "Hi"
  fi    
    echo "Best School"
    ((count ++))
done
