#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and "Hi" after "Best School" on the 9th iteration using a while loop

count=1
while [ "$count" -le 10 ]; do
  if [ "$count" -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done
