#!/usr/bin/env bash
#This script will display number from 1-20 with some cases at 4,9, and 17 iteration

count=1
while [ "$count" -le 20 ]; do
case $count in
   4)
    echo "$count"
    echo "bad luck from china"
    ;;
   9)
    echo "$count"
    echo "bad luck from japan"
    ;;
   17)
    echo "$count"
    echo "bad luck from italy"
    ;;
   *)
    echo "$count"
    ;;
esac
((count++))
done
